// 進階課程日文翻譯
export const advancedCoursesJa = [
  {
    id: "adv-1-1",
    week: 5,
    module: 1,
    title: "高度なプロンプトの技術",
    description: "ROPEフレームワークと高度なプロンプト技術を習得し、完璧な指示を作成する",
    pages: [],
    duration_minutes: 45,
  },
  {
    id: "adv-2-1",
    week: 6,
    module: 1,
    title: "マルチモーダルアプリケーション",
    description: "視覚、音声、ビデオ分析とGemini Liveの実践",
    pages: [],
    duration_minutes: 50,
  },
  {
    id: "adv-3-1",
    week: 7,
    module: 1,
    title: "カスタムAIの構築",
    description: "個性化されたAIアシスタント（Gems）の作成と管理、カスタマイズされたワークフローの実装",
    pages: [],
    duration_minutes: 50,
  },
  {
    id: "adv-4-1",
    week: 8,
    module: 1,
    title: "AI リテラシーと事実確認",
    description: "幻覚の識別、事実確認、倫理的配慮、批判的思考力",
    pages: [],
    duration_minutes: 45,
  },
  {
    id: "adv-5-1",
    week: 9,
    module: 1,
    title: "Gemini 3.1 Pro 実戦ワークショップ",
    description: "Deep Research完全ワークフロー、Veo 3.1高度な応用、高度なモデルのコスト効益分析",
    pages: [],
    duration_minutes: 50,
  },
  {
    id: "adv-6-1",
    week: 10,
    module: 1,
    title: "AI時代の意思決定管理",
    description: "AI洞察に基づく意思決定、KPI設定、失敗事例分析、チームリーダーシップの新しいモデル",
    pages: [],
    duration_minutes: 50,
  },
];
